# Webb Relayer Network Port to run on
# default: 9955
port = 9955

# Features to only allow for data-querying in the relayer
# By default, all are true, so hence need to disable the rest
[features]
data-query = true
governance-relay = false
private-tx-relay = false
