port = 9955

[substrate.webbtangle]
enabled=true
chain-id=1080
http-endpoint = "https://standalone.webb.tools"
ws-endpoint = "wss://standalone.webb.tools"
runtime = "WebbProtocol"
suri = "$TANGLE_MIXER_SURI"
pallets = []
