# Webb Relayer Network Port to run on
# default: 9955
port = 9955

# Features to only allow for private transaction relaying in the relayer
# By default, all are true, so hence need to disable the rest
[features]
private-tx-relay = true
governance-relay = false
data-query = false
