[eth2.sepolia]
# The name that the chain is indexed on, for linkable anchors
name = "sepolia-testnet"
# Http(s) Endpoint for quick Req/Res
http-endpoint = "$SEPOLIA_MAINNET_HTTP_URL"
# Websocket Endpoint for long living connections
ws-endpoint = "$SEPOLIA_MAINNET_WS_URL"
# chain specific id from evm opcode
chain-id = 5002
# The Private Key of this account on this network
# the format is more dynamic here:
# 1. if it starts with '0x' then this would be raw (64 bytes) hex encoded
#    private key.
#    Example: 0x8917174396171783496173419137618235192359106130478137647163400318
#
# 2. if it starts with '$' then it would be considered as an Enviroment variable
#    of a hex-encoded private key.
#    Example: $RINKEBY_PRIVATE_KEY
#
# 3. if it starts with '> ' then it would be considered as a command that
#    the relayer would execute and the output of this command would be the
#    hex encoded private key.
#    Example: > ./getKey.sh rinkeby-privatekey
#
# 4. if it doesn't contains special characters and has 12 or 24 words in it
#    then we should process it as a mnemonic string: 'word two three four ...'
private-key = "$SEPOLIA_MAINNET_PRIVATE_KEY"
# block header relay flag
block-header-relay = true
# light-client rpc url
light-client-rpc-url = "$SEPOLIA_MAINNET_LIGHT_CLIENT_RPC_URL"